[project]
name = "mc-python-plugins"
version = "0.1.0"
description = "Shared Python tooling for Minecraft plugins"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}

[project.optional-dependencies]
dev = ["black", "flake8"]
